#!/usr/bin/env python3
"""Generate the Phase-2 Smart Actions earcon vocabulary for all themes.

Adds the following earcons to every theme directory under sounds/themes/:

  capture_started   - rising two-tone, "voice capture begins"
  capture_saved     - warm low tone, "your thought is safe"
  agent_routing     - soft pulse, "sending to agent"
  agent_response    - descending two-tone, "reply received"
  confirm_required  - distinct alert, "needs approval" (not alarming)
  action_complete   - brief success ping, "tool call done"
  thinking_pulse    - very soft low blip, played at 1 Hz while waiting

Existing earcons (start, stop, success, error) are NOT touched -- those are
generated by scripts/generate_sounds.py / generate_sounds_hq.py and are
tuned by hand. This script only writes the new names.

Pipeline:

  - 44.1 kHz, mono, 16-bit PCM (matches existing assets)
  - Each earcon has a base recipe; per-theme tuning swaps timbre and tempo
  - Cosine fade-in / fade-out to avoid clicks
  - All tones normalized to a peak just under unity to prevent clipping

Run:  python scripts/generate_earcons.py
"""

import math
import struct
import sys
import wave
from pathlib import Path

SAMPLE_RATE = 44100

# Per-theme tuning. Each tuple is (pitch_scale, duration_scale, harmonic_boost,
# headroom_db). pitch_scale shifts every base frequency; duration_scale stretches
# attack/release; harmonic_boost adds presence; headroom is a per-theme volume
# trim so quiet themes stay quiet.
THEMES = {
    'cute':    {'pitch': 1.20, 'dur': 0.90, 'harm': 0.35, 'gain': 0.55},
    'chirpy':  {'pitch': 1.35, 'dur': 0.75, 'harm': 0.45, 'gain': 0.50},
    'warm':    {'pitch': 0.70, 'dur': 1.25, 'harm': 0.20, 'gain': 0.45},
    'zen':     {'pitch': 0.85, 'dur': 1.40, 'harm': 0.55, 'gain': 0.40},
    'classic': {'pitch': 1.00, 'dur': 1.00, 'harm': 0.10, 'gain': 0.55},
}


# ---------------------------------------------------------------------------
# Low-level synthesis helpers
# ---------------------------------------------------------------------------

def _cosine_fade(samples, fade_in=0.008, fade_out=0.04):
    """Apply cosine fade-in/out in-place to avoid clicks."""
    n = len(samples)
    n_in = int(SAMPLE_RATE * fade_in)
    n_out = int(SAMPLE_RATE * fade_out)
    for i in range(min(n_in, n)):
        f = 0.5 * (1 - math.cos(math.pi * i / max(n_in, 1)))
        samples[i] *= f
    for i in range(min(n_out, n)):
        f = 0.5 * (1 - math.cos(math.pi * i / max(n_out, 1)))
        samples[n - 1 - i] *= f


def _tone(t, freq, harm=0.2):
    """Sine + faint upper harmonics for a fuller (not buzzy) tone."""
    phase = 2 * math.pi * freq * t
    s = math.sin(phase)
    if harm > 0:
        s += harm * math.sin(2 * phase)
        s += (harm * 0.4) * math.sin(3 * phase)
    return s / (1 + 1.4 * harm)  # rough normalize so harm doesn't blow gain


def _write_wav(path, samples, gain=0.6):
    """Normalize to peak * gain, clip, and write a mono 16-bit WAV."""
    peak = max((abs(s) for s in samples), default=1.0) or 1.0
    scale = (32767 * gain) / peak
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), 'w') as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(SAMPLE_RATE)
        for s in samples:
            v = int(max(-32767, min(32767, s * scale)))
            wav.writeframes(struct.pack('<h', v))


def _silence(seconds):
    return [0.0] * int(SAMPLE_RATE * seconds)


# ---------------------------------------------------------------------------
# Per-earcon recipes. Each takes the theme tuning and returns sample list.
# ---------------------------------------------------------------------------

def make_capture_started(tune):
    """Rising two-tone: clear "I heard you" cue."""
    pitch, dur_k, harm = tune['pitch'], tune['dur'], tune['harm']
    duration = 0.16 * dur_k
    f1 = 620 * pitch
    f2 = 880 * pitch

    n = int(SAMPLE_RATE * duration)
    samples = [0.0] * n
    split = int(n * 0.45)
    for i in range(n):
        t = i / SAMPLE_RATE
        if i < split:
            samples[i] = _tone(t, f1, harm) * 0.8
        else:
            t2 = (i - split) / SAMPLE_RATE
            samples[i] = _tone(t2, f2, harm) * 0.9
    _cosine_fade(samples, 0.006, 0.025)
    return samples


def make_capture_saved(tune):
    """Warm low confirmation tone: 'your thought is safe'."""
    pitch, dur_k, harm = tune['pitch'], tune['dur'], tune['harm']
    duration = 0.22 * dur_k
    # Slight descent (resolution feel)
    f_start = 460 * pitch
    f_end = 360 * pitch

    n = int(SAMPLE_RATE * duration)
    samples = [0.0] * n
    for i in range(n):
        t = i / SAMPLE_RATE
        prog = i / max(n - 1, 1)
        freq = f_start + (f_end - f_start) * prog
        # Slow tremolo on the harmonics gives the "warm" feel without buzz
        warmth = 1.0 + 0.15 * math.sin(2 * math.pi * 4 * t)
        samples[i] = _tone(t, freq, harm * warmth) * 0.9
    _cosine_fade(samples, 0.012, 0.06)
    return samples


def make_agent_routing(tune):
    """Soft single pulse: 'sending'."""
    pitch, dur_k, harm = tune['pitch'], tune['dur'], tune['harm']
    duration = 0.13 * dur_k
    freq = 720 * pitch

    n = int(SAMPLE_RATE * duration)
    samples = [0.0] * n
    for i in range(n):
        t = i / SAMPLE_RATE
        # Quick attack, soft body
        env = (1 - math.exp(-t * 90)) * math.exp(-t * 10)
        samples[i] = _tone(t, freq, harm) * env
    _cosine_fade(samples, 0.005, 0.02)
    return samples


def make_agent_response(tune):
    """Descending two-tone: 'reply received'. Mirrors capture_started."""
    pitch, dur_k, harm = tune['pitch'], tune['dur'], tune['harm']
    duration = 0.22 * dur_k
    f1 = 920 * pitch
    f2 = 620 * pitch

    n = int(SAMPLE_RATE * duration)
    samples = [0.0] * n
    split = int(n * 0.40)
    for i in range(n):
        t = i / SAMPLE_RATE
        if i < split:
            samples[i] = _tone(t, f1, harm) * 0.85
        else:
            t2 = (i - split) / SAMPLE_RATE
            samples[i] = _tone(t2, f2, harm) * 0.95
    _cosine_fade(samples, 0.006, 0.035)
    return samples


def make_confirm_required(tune):
    """Distinct alert, attention-grabbing but not alarming.

    Two repeats of a mid-frequency dyad. Slight pitch wobble between repeats
    differentiates it from action_complete and from error.
    """
    pitch, dur_k, harm = tune['pitch'], tune['dur'], tune['harm']
    blip_dur = 0.09 * dur_k
    gap_dur = 0.05 * dur_k
    f_low = 540 * pitch
    f_high = 680 * pitch

    def _blip(detune):
        n = int(SAMPLE_RATE * blip_dur)
        out = [0.0] * n
        for i in range(n):
            t = i / SAMPLE_RATE
            env = (1 - math.exp(-t * 120)) * math.exp(-t * 14)
            s = (_tone(t, f_low * detune, harm) + _tone(t, f_high * detune, harm)) * 0.5
            out[i] = s * env
        return out

    samples = []
    samples.extend(_blip(1.00))
    samples.extend(_silence(gap_dur))
    samples.extend(_blip(1.04))
    _cosine_fade(samples, 0.005, 0.025)
    return samples


def make_action_complete(tune):
    """Brief success ping. Distinct from the longer 'success' earcon."""
    pitch, dur_k, harm = tune['pitch'], tune['dur'], tune['harm']
    duration = 0.15 * dur_k
    # Octave jump up
    f1 = 660 * pitch
    f2 = 990 * pitch

    n = int(SAMPLE_RATE * duration)
    samples = [0.0] * n
    split = int(n * 0.35)
    for i in range(n):
        t = i / SAMPLE_RATE
        if i < split:
            samples[i] = _tone(t, f1, harm) * 0.8
        else:
            t2 = (i - split) / SAMPLE_RATE
            samples[i] = _tone(t2, f2, harm) * 0.95
    _cosine_fade(samples, 0.005, 0.03)
    return samples


def make_thinking_pulse(tune):
    """Very soft low blip. Fires at 1 Hz -- must NOT be annoying when repeated.

    Kept short (~70 ms) and low-frequency, with a soft attack and exponential
    decay. Per-theme gain is also halved so it sits well under everything else.
    """
    pitch, dur_k, harm = tune['pitch'], tune['dur'], tune['harm']
    duration = 0.07 * dur_k
    freq = 220 * pitch  # always sub-mid range so it doesn't compete with speech

    n = int(SAMPLE_RATE * duration)
    samples = [0.0] * n
    for i in range(n):
        t = i / SAMPLE_RATE
        env = (1 - math.exp(-t * 60)) * math.exp(-t * 25)
        # Suppress harmonics -- a clean low sine is the least irritating shape
        samples[i] = math.sin(2 * math.pi * freq * t) * env
    _cosine_fade(samples, 0.005, 0.025)
    return samples


# Map earcon name -> recipe, plus a per-earcon gain multiplier so we can
# pull thinking_pulse down independently of the theme's overall gain.
EARCONS = {
    'capture_started':  (make_capture_started,  1.00),
    'capture_saved':    (make_capture_saved,    1.00),
    'agent_routing':    (make_agent_routing,    0.85),
    'agent_response':   (make_agent_response,   1.00),
    'confirm_required': (make_confirm_required, 1.00),
    'action_complete':  (make_action_complete,  0.95),
    'thinking_pulse':   (make_thinking_pulse,   0.45),  # MUST stay quiet
}


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def generate_theme(theme_name, tune, themes_root, overwrite=False):
    theme_dir = themes_root / theme_name
    written = []
    skipped = []
    for name, (recipe, name_gain) in EARCONS.items():
        out_path = theme_dir / f"{name}.wav"
        if out_path.exists() and not overwrite:
            skipped.append(name)
            continue
        samples = recipe(tune)
        gain = tune['gain'] * name_gain
        _write_wav(out_path, samples, gain=gain)
        written.append(name)
    print(f"  {theme_name}: wrote {len(written)} new, skipped {len(skipped)} existing")
    if written:
        print(f"    + {', '.join(written)}")
    if skipped:
        print(f"    = {', '.join(skipped)} (already present; use --force to overwrite)")


def main(argv=None):
    argv = argv or sys.argv[1:]
    overwrite = '--force' in argv

    repo_root = Path(__file__).resolve().parent.parent
    themes_root = repo_root / 'sounds' / 'themes'
    if not themes_root.exists():
        print(f"[ERROR] Themes directory not found: {themes_root}")
        return 1

    print(f"Generating earcons under {themes_root}")
    print(f"  overwrite={'YES' if overwrite else 'no'}")
    for theme_name, tune in THEMES.items():
        if not (themes_root / theme_name).exists():
            print(f"  [SKIP] theme dir missing: {theme_name}")
            continue
        generate_theme(theme_name, tune, themes_root, overwrite=overwrite)

    print("\nDone. Phase-2 earcons available in every theme directory.")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
