@echo off
rem Build the Samsara installer (installer\samsara.iss, Inno Setup 6) from a
rem finished PyInstaller dist -- the same dist the release ZIP is packaged
rem from -- into dist\SamsaraSetup-<version>.exe.
rem
rem   tools\build_installer.cmd [manifest.json]
rem
rem The version is read from samsara\__init__.py (the one source the build
rem and tools\check_release_version.py use), never typed here. Component
rem sizes and the command model's availability are read from manifest.json
rem (tools\gen_release_manifest.py's output; default: .\manifest.json, or the
rem path given as the first argument) and written to
rem installer\manifest_defines.iss, which samsara.iss includes. Without a
rem manifest the installer still builds, with unknown sizes.
rem
rem Requires: dist\Samsara\Samsara.exe (build first), ISCC.exe (Inno Setup 6;
rem set SAMSARA_ISCC to override the lookup), Python 3.11 for the two reads.

setlocal EnableExtensions EnableDelayedExpansion

set "REPO=%~dp0.."
pushd "%REPO%" || exit /b 1

set "PYTHON_ARGS=%SAMSARA_PYTHON_ARGS%"
if defined SAMSARA_PYTHON (
    set "PYTHON_EXE=%SAMSARA_PYTHON:"=%"
) else if exist "F:\envs\sami\python.exe" (
    set "PYTHON_EXE=F:\envs\sami\python.exe"
) else (
    where py >nul 2>nul
    if not errorlevel 1 (
        set "PYTHON_EXE=py"
        set "PYTHON_ARGS=-3.11"
    ) else (
        where python >nul 2>nul
        if not errorlevel 1 set "PYTHON_EXE=python"
    )
)
if not defined PYTHON_EXE (
    echo Python was not found. Set SAMSARA_PYTHON to a Python 3.11 executable.
    popd & exit /b 1
)

if not exist "dist\Samsara\Samsara.exe" (
    echo dist\Samsara\Samsara.exe is missing -- build first ^(python -m PyInstaller scripts\samsara.spec^).
    popd & exit /b 1
)

if defined SAMSARA_ISCC (
    set "ISCC=%SAMSARA_ISCC:"=%"
) else if exist "%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe" (
    set "ISCC=%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe"
) else if exist "%ProgramFiles%\Inno Setup 6\ISCC.exe" (
    set "ISCC=%ProgramFiles%\Inno Setup 6\ISCC.exe"
) else (
    where iscc >nul 2>nul
    if not errorlevel 1 set "ISCC=iscc"
)
if not defined ISCC (
    echo Inno Setup 6 ^(ISCC.exe^) was not found. Install it or set SAMSARA_ISCC.
    popd & exit /b 1
)

rem ---- version: the same source as the build ---------------------------
for /f "usebackq delims=" %%V in (`"%PYTHON_EXE%" %PYTHON_ARGS% -c "import sys; sys.path.insert(0, '.'); from pathlib import Path; from tools.check_release_version import _string_assignment; print(_string_assignment(Path('samsara/__init__.py'), '__version__'))"`) do set "APP_VERSION=%%V"
if not defined APP_VERSION (
    echo Could not read __version__ from samsara\__init__.py.
    popd & exit /b 1
)

rem ---- component sizes from the manifest -------------------------------
set "MANIFEST=%~1"
if not defined MANIFEST set "MANIFEST=manifest.json"
if exist "%MANIFEST%" (
    "%PYTHON_EXE%" %PYTHON_ARGS% -c "import json, sys; d = json.load(open(sys.argv[1], encoding='utf-8')); by = {c['id']: c for c in d['components']}; names = {'cuda-pack': 'CudaPack', 'wake-word-models': 'WakeWordModels', 'command-model': 'CommandModel', 'gesture-control': 'GestureControl'}; lines = ['; generated by tools\\build_installer.cmd from ' + sys.argv[1] + ' -- do not edit']; [lines.append('#define %sSize %d' % (n, by[i]['size_bytes'] or 0)) for i, n in names.items() if i in by]; [lines.append('#define %sAvailable %d' % (n, 1 if by[i]['available'] else 0)) for i, n in names.items() if i in by]; lines.append('#define ManifestReleaseTag \"%s\"' % d['release_tag']); open('installer/manifest_defines.iss', 'w', encoding='ascii', newline='\r\n').write('\n'.join(lines) + '\n'); print('installer\\manifest_defines.iss written from', sys.argv[1])" "%MANIFEST%"
    if errorlevel 1 (
        echo Could not read %MANIFEST%.
        popd & exit /b 1
    )
) else (
    echo No manifest at %MANIFEST% -- component sizes will show as unknown.
    if exist "installer\manifest_defines.iss" del "installer\manifest_defines.iss"
)

echo Building SamsaraSetup-%APP_VERSION%.exe with "%ISCC%"
"%ISCC%" /Qp "/DAppVersion=%APP_VERSION%" "/DDistDir=%REPO%\dist\Samsara" "/DOutputDir=%REPO%\dist" "installer\samsara.iss"
if errorlevel 1 (
    echo ISCC failed.
    popd & exit /b 1
)
if not exist "dist\SamsaraSetup-%APP_VERSION%.exe" (
    echo ISCC reported success but dist\SamsaraSetup-%APP_VERSION%.exe is missing.
    popd & exit /b 1
)
echo Built dist\SamsaraSetup-%APP_VERSION%.exe
popd
exit /b 0
