"""Canonical-command report (queue 45): resolution problems, sound-alike
pairs, declared undo and destructive flags, and every command's canonical
spoken form -- derived from the live registry through samsara/command_catalog.py.

This does not generate a second catalogue: commands_catalog.json (written by
tools/gen_command_catalog.py) stays the one machine-readable table. This tool
only renders the queue-45 views of it as Markdown, deterministically.

Usage:
    F:\\envs\\sami\\python.exe tools\\command_canonical_report.py               # Markdown to stdout
    F:\\envs\\sami\\python.exe tools\\command_canonical_report.py --out FILE    # write FILE

Run with SAMSARA_HOME_DIR pointed at a scratch directory when a Samsara
instance is running, so tooling never attaches a handler to its live log.
"""
from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from samsara import command_catalog as cc  # noqa: E402


def build():
    from tools.dump_command_metadata import build_executor  # noqa: PLC0415
    executor = build_executor()
    specs = cc.build_catalog(executor)
    claims = cc.raw_phrase_claims(executor)
    metadata = cc.registry_metadata(executor)
    return specs, claims, metadata


def _cell(text) -> str:
    return str(text).replace("|", "\\|")


def render(specs, claims, metadata) -> str:
    rows = cc.resolution_rows(specs, claims)
    pairs = cc.sound_alike_pairs(specs)
    undo = {s.canonical_id: cc.declared_undo(metadata.get(s.canonical_id)) for s in specs}
    undo_counts = Counter(str(v).lower() for v in undo.values())
    n_phrases = len({a for s in specs for a in s.aliases} | set(claims))
    out = [
        "# Canonical command report",
        "",
        "Generated by `tools/command_canonical_report.py` from the live registry. Do not edit.",
        "",
        f"- commands (canonical forms): {len(specs)} "
        f"(builtin {sum(1 for s in specs if s.kind == 'builtin')}, plugin {sum(1 for s in specs if s.kind == 'plugin')})",
        f"- distinct phrases (claimed or live): {n_phrases}",
        f"- phrases not resolving to exactly one command: {len(rows)} "
        f"(zero {sum(1 for r in rows if r['status'] == 'zero')}, many {sum(1 for r in rows if r['status'] == 'many')})",
        f"- sound-alike pairs across different commands: {len(pairs)} "
        f"(confusion {sum(1 for p in pairs if p[4] == 'confusion')}, one_letter {sum(1 for p in pairs if p[4] == 'one_letter')})",
        f"- undo declared: true {undo_counts.get('true', 0)}, false {undo_counts.get('false', 0)}, "
        f"unknown {undo_counts.get('unknown', 0)}",
        f"- destructive: {sum(1 for s in specs if cc.is_destructive(s))}",
        "",
        "## Phrases that do not resolve to exactly one command",
        "",
        "| phrase | status | claimed by | live registry resolves to |",
        "|---|---|---|---|",
    ]
    for r in rows:
        out.append(f"| `{_cell(r['phrase'])}` | {r['status']} | {', '.join(f'`{i}`' for i in r['claimed_by']) or '-'} | "
                   f"{', '.join(f'`{i}`' for i in r['resolves_to']) or 'nothing'} |")
    out += ["", "## Sound-alike pairs (different commands)", "",
            "| phrase A | phrase B | command A | command B | rule |", "|---|---|---|---|---|"]
    for a, b, ia, ib, rule in pairs:
        out.append(f"| `{_cell(a)}` | `{_cell(b)}` | `{ia}` | `{ib}` | {rule} |")
    out += ["", "## Commands", "",
            "| canonical id | canonical form | plugin | undo (declared) | destructive | aliases |",
            "|---|---|---|---|---|---|"]
    for s in specs:
        out.append(f"| `{s.canonical_id}` | `{_cell(cc.canonical_form(s))}` | {s.plugin} | "
                   f"{str(undo[s.canonical_id]).lower()} | {'yes' if cc.is_destructive(s) else 'no'} | {len(s.aliases)} |")
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path)
    args = parser.parse_args(argv)
    text = render(*build())
    if args.out:
        args.out.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {args.out}")
    else:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
